[build]
functions = "functions/"

[context.deploy-preview.environment]
  AWS_LAMBDA_JS_RUNTIME = "nodejs18.x"
  TEST=deploy-preview

[context.branch-deploy.environment]
  AWS_LAMBDA_JS_RUNTIME = "nodejs18.x"
  TEST=branch-deploy
