[build]
functions = "functions/"
included_files = ["./prisma/**", "./node_modules/.prisma/client/**", "./app/prisma-client/**/*"]

[context.branch-deploy.environment]
  AWS_LAMBDA_JS_RUNTIME = "nodejs20.x"
